// DO NOT EDIT, AUTOMATICALLY GENERATED BY generate.js

/// An enum describing how to interpret the value of a UserEvent.
public enum Unit: Int {
    /// We want to count how many times something happened in total.
    case count
    /// We want to measure how long something takes with millisecond precision.
    case milliseconds
    /// We want to measure how long something takes with second precision.
    case seconds

    var stringValue: String {
        get {
            switch self {
            case .count:
                return "count"
            case .milliseconds:
                return "milliseconds"
            case .seconds:
                return "seconds"
            }
        }
    }

    static func from(string: String) -> Unit? {
        switch string {
        case "count":
            return .count
        case "milliseconds":
            return .milliseconds
        case "seconds":
            return .seconds
        default:
            return nil
        }
    }
}

/// A time-based unit grouping the milliseconds and seconds Units.
public enum TimeUnitGroup: Int {
    /// See Unit.milliseconds
    case milliseconds
    /// See Unit.seconds
    case seconds

    var unitValue: Unit {
        get {
            switch self {
            case .milliseconds:
                return .milliseconds
            case .seconds:
                return .seconds
            }
        }
    }
}
